http:
  host: "localhost"
  port: 8080

db:
  player:
    dsn: "postgres://postgres:password@10.176.112.178:5432/scs_player?sslmode=disable&connect_timeout=5"

secrets:
  jwt-secret-key: "your-jwt-secret-key"
